package com.solarflare.firmware.model;

public enum FirmwareType {
	
	FIRMWARE_TYPE_PHY,
	FIRMWARE_TYPE_PHY_LOADER,
	FIRMWARE_TYPE_BOOTROM,
	FIRMWARE_TYPE_MCFW,
	FIRMWARE_TYPE_MCFW_BACKUP,
	FIRMWARE_TYPE_DISABLED_CALLISTO,
	FIRMWARE_TYPE_FPGA,
	FIRMWARE_TYPE_FPGA_BACKUP,
	FIRMWARE_TYPE_FCFW,
	FIRMWARE_TYPE_FCFW_BACKUP,
	FIRMWARE_TYPE_CPLD,
	FIRMWARE_TYPE_MUMFW,
	FIRMWARE_TYPE_UEFIROM,
			
}